# Generated by Django 3.2.20 on 2023-08-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('unidad_medida', models.CharField(max_length=100, verbose_name='Unidad de medida')),
            ],
        ),
    ]
