# Generated by Django 3.2.20 on 2023-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='valor',
            field=models.IntegerField(default=None, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
