# Generated by Django 3.2.20 on 2023-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0002_metrica_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='valor',
            field=models.IntegerField(default=0, verbose_name='Valor'),
        ),
    ]
