# Generated by Django 3.2.20 on 2023-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0004_auto_20230815_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='frecuencia',
            field=models.CharField(choices=[('Bianual', 'Bianual'), ('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='descripcion',
            field=models.TextField(max_length=100, null=True, verbose_name='Descripcion'),
        ),
    ]
