# Generated by Django 4.2.4 on 2023-08-17 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0004_auto_20230816_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='descripcion',
            field=models.TextField(max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='frecuencia',
            field=models.CharField(choices=[('Bianual', 'Bianual'), ('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='titulo',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre no puede contener caracteres especiales.', regex='^[a-zA-Z\\s]*$')], verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='unidad_medida',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='La unidad de medida no puede contener caracteres especiales', regex='^[a-zA-Z\\s]*$')], verbose_name='Unidad de Medida'),
        ),
    ]
