# Generated by Django 3.2.20 on 2023-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0005_auto_20230815_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='frecuencia',
            field=models.CharField(choices=[('Bianual', 'Bianual'), ('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual')], max_length=10),
        ),
    ]
