# Generated by Django 4.2.4 on 2023-08-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0005_metrica_year_alter_metrica_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ingrese año:'),
        ),
        migrations.CreateModel(
            name='HistorialMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_historico', models.PositiveIntegerField()),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIReApp.metrica')),
            ],
        ),
    ]
