# Generated by Django 4.2.4 on 2023-08-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0006_alter_metrica_year_historialmetrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmetrica',
            name='valor_historico',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
