# Generated by Django 4.2.4 on 2023-08-30 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0007_historialmetrica_valor_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre no puede contener caracteres especiales.', regex='^[a-zA-Z\\s]*$')], verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=100, null=True, verbose_name='Descripción')),
                ('ambito', models.CharField(choices=[('Fin', 'Fin'), ('Propósito', 'Propósito'), ('Componente', 'Componente'), ('Actividades', 'Actividades')], max_length=20)),
                ('tipo', models.CharField(choices=[('Eficiencia', 'Eficiencia'), ('Eficacia', 'Eficacia'), ('Economía', 'Economía'), ('Calidad', 'Calidad')], max_length=10)),
            ],
        ),
    ]
