# Generated by Django 4.2.4 on 2023-08-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0008_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='frecuencia',
            field=models.CharField(choices=[('Bianual', 'Bianual'), ('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual')], default=2, max_length=10, verbose_name='Frecuencia de medición'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='ambito',
            field=models.CharField(choices=[('Fin', 'Fin'), ('Propósito', 'Propósito'), ('Componente', 'Componente'), ('Actividades', 'Actividades')], max_length=20, verbose_name='¿Qué se está midiendo?'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tipo',
            field=models.CharField(choices=[('Eficiencia', 'Eficiencia'), ('Eficacia', 'Eficacia'), ('Economía', 'Economía'), ('Calidad', 'Calidad')], max_length=10, verbose_name='Tipo'),
        ),
    ]
