# Generated by Django 3.2.20 on 2023-09-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0011_auto_20230901_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='metrica',
            name='comida',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MIReApp.comidas'),
            preserve_default=False,
        ),
    ]
