# Generated by Django 3.2.20 on 2023-09-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0011_auto_20230901_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='denominador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Denominador', to='MIReApp.metrica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='denominador_u_medida',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='indicador',
            name='denominador_valor',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='indicador',
            name='formula',
            field=models.CharField(max_length=100, null=True, verbose_name='Formula'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='numerador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Numerador', to='MIReApp.metrica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='numerador_u_medida',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='indicador',
            name='numerador_valor',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='indicador',
            name='resultado',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
    ]
