# Generated by Django 3.2.20 on 2023-09-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0012_auto_20230918_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='denominador_u_medida',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='denominador_valor',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='formula',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Formula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_u_medida',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_valor',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='resultado',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name=''),
            preserve_default=False,
        ),
    ]
