# Generated by Django 3.2.20 on 2023-09-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0013_comidas_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIReApp.indicador'),
        ),
    ]
