# Generated by Django 3.2.20 on 2023-09-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0013_auto_20230918_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='denominador',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='denominador_u_medida',
            field=models.PositiveIntegerField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='denominador_valor',
            field=models.PositiveIntegerField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='formula',
            field=models.CharField(blank=True, choices=[('Promedio', 'Promedio'), ('Tasa de Variacion', 'Tasa de Variacion'), ('Inversion Promedio', 'Inversion Promedio')], max_length=20, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_u_medida',
            field=models.PositiveIntegerField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_valor',
            field=models.PositiveIntegerField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='resultado',
            field=models.PositiveIntegerField(blank=True, verbose_name=''),
        ),
    ]
