# Generated by Django 3.2.20 on 2023-09-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0014_auto_20230918_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='denominador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='denominador_u_medida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='denominador_valor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_u_medida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_valor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='resultado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
