# Generated by Django 3.2.20 on 2023-09-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0014_auto_20230919_1656'),
        ('MIReApp', '0015_auto_20230918_1440'),
    ]

    operations = [
    ]
