# Generated by Django 3.2.20 on 2023-09-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0016_merge_0014_auto_20230919_1656_0015_auto_20230918_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comidas',
        ),
        migrations.RemoveField(
            model_name='metrica',
            name='comida',
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MIReApp.metrica'),
            preserve_default=False,
        ),
    ]
