# Generated by Django 3.2.20 on 2023-09-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0017_auto_20230919_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='denominador_periodo',
            field=models.IntegerField(default=None, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='numerador_periodo',
            field=models.IntegerField(default=None, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='formula',
            field=models.CharField(blank=True, choices=[('Promedio', 'Promedio'), ('Tasa de Variacion', 'Tasa de Variacion'), ('Porcentaje', 'Porcentaje')], max_length=20, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
    ]
