# Generated by Django 3.2.20 on 2023-09-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0018_auto_20230919_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='denominador_u_medida',
            new_name='denominador_medida',
        ),
        migrations.RenameField(
            model_name='indicador',
            old_name='numerador_u_medida',
            new_name='numerador_medida',
        ),
    ]
