# Generated by Django 3.2.20 on 2023-09-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0019_auto_20230920_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='denominador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Denominador', to='MIReApp.metrica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='denominador_periodo',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Numerador', to='MIReApp.metrica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_periodo',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
