# Generated by Django 3.2.20 on 2023-09-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0020_auto_20230920_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='denominador_periodo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Instancia_Denominador', to='MIReApp.historialmetrica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_periodo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Instancia_Numerador', to='MIReApp.historialmetrica'),
            preserve_default=False,
        ),
    ]
