# Generated by Django 3.2.20 on 2023-09-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0022_auto_20230921_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
