# Generated by Django 3.2.20 on 2023-09-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0023_alter_indicador_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='denominador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Denominador', to='MIReApp.metrica'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='denominador_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Instancia_Denominador', to='MIReApp.historialmetrica'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Numerador', to='MIReApp.metrica'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='numerador_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Instancia_Numerador', to='MIReApp.historialmetrica'),
        ),
    ]
