# Generated by Django 3.2.20 on 2023-09-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0024_auto_20230922_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
