# Generated by Django 3.2.20 on 2023-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0026_alter_indicador_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmetrica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
