# Generated by Django 3.2.20 on 2023-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0027_alter_historialmetrica_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
