# Generated by Django 3.2.20 on 2023-10-03 22:54

import MIReApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0028_indicador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='month',
            field=models.CharField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10, null=True, verbose_name='Ingrese mes:'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='semestral',
            field=models.CharField(blank=True, choices=[('Enero-Junio', 'Enero-Junio'), ('Julio-Diciembre', 'Julio-Diciembre')], max_length=15, null=True, verbose_name='Ingrese semestre:'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='year2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Segundo año'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='frecuencia',
            field=models.CharField(choices=[('Cuatrienal', 'Cuatrienal'), ('Bianual', 'Bianual'), ('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual')], default='Anual', max_length=10, verbose_name='Frecuencia de medición'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='frecuencia',
            field=models.CharField(choices=[('Cuatrienal', 'Cuatrienal'), ('Bianual', 'Bianual'), ('Anual', 'Anual'), ('Semestral', 'Semestral'), ('Mensual', 'Mensual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[MIReApp.models.validate_year], verbose_name='Ingrese año:'),
        ),
    ]
