# Generated by Django 4.2.4 on 2023-10-21 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0032_auto_20231020_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programa',
            name='duracion',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(default='', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre no puede contener caracteres especiales.', regex='^[a-zA-Z\\s]*$')], verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programa',
            name='objetivo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
