# Generated by Django 3.2.20 on 2023-10-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0033_alter_programa_descripcion_alter_programa_duracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='programa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MIReApp.programa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='objetivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MIReApp.objetivos'),
            preserve_default=False,
        ),
    ]
