# Generated by Django 3.2.20 on 2023-10-24 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0034_auto_20231024_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MIReApp.objetivos'),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='programa',
            field=models.PositiveIntegerField(),
        ),
    ]
