# Generated by Django 3.2.20 on 2023-10-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0035_auto_20231024_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='objetivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
