# Generated by Django 3.2.20 on 2023-10-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0036_alter_programa_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos',
            name='nombre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
