# Generated by Django 3.2.20 on 2023-10-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0037_alter_objetivos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MIReApp.programa'),
        ),
    ]
