# Generated by Django 3.2.20 on 2023-10-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0038_alter_indicador_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
