# Generated by Django 3.2.20 on 2023-10-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0039_alter_objetivos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
    ]
