# Generated by Django 3.2.20 on 2023-12-06 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0043_auto_20231206_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(default=None, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre no puede contener caracteres especiales.', regex='^[a-zA-Z\\s]*$')], verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
