# Generated by Django 3.2.20 on 2023-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0044_indicador_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.AddField(
            model_name='user',
            name='semestre_historico',
            field=models.CharField(blank=True, choices=[('Ingeniería en Sistemas de Información', 'Ingeniería en Sistemas de Información'), ('Ingeniería Química', 'Ingeniería Química'), ('Ingeniería Electromecánica', 'Ingeniería Electromecánica'), ('Materias Básicas', 'Materias Básicas')], max_length=40, null=True, verbose_name='Ingrese área:'),
        ),
    ]
