# Generated by Django 3.2.20 on 2023-12-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIReApp', '0045_auto_20231206_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='semestre_historico',
            new_name='area',
        ),
    ]
