# Generated by Django 4.2.3 on 2023-07-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrica',
            name='nombre',
        ),
    ]
